### PR TITLE
DigitalOcean object storage support - fixed area code error - refactor some code

### PR DESCRIPTION
**Pull request by rakibabu**
1. Added endpoint to module to configuration. This is required because the url for digitaloacean is different.(https://[bucket].[region].digitaloaceanspaces.com)
2. Fixed bug in module, area code is not set. Added try catch.
3. Refactored some options to set options

### CODE REVIEW

**Comment by rakibabu** [comment]
Hi @thaiphan ,

Any update for me on this pull request?

Kind regards,

Rakhal Imming

**Comment by thaiphan** [comment]
Hi @rakibabu,

Thanks for contributing! The "area code is not set" bug fix is great and I'll be happy to merge that in as a separate pull request.

However, even if the S3 client is compatible with Digital Ocean, I'm not keen on combining the configurations and command line options for S3 and Digital Ocean configurations into the same files like you've done here. I think in order for the change to be merged in, I'll require you to make the following changes:

- Separate out the Digital Ocean commands into separate classes (you can even just extend the S3 classes if it makes that easier)
- Separate out the Digital Ocean configuration into its own section
- As part of the separate Digital Ocean configuration, make sure to include all the available regions (not just Amsterdam)

If you can make those changes, I'll be happy to merge in your pull request!

Regards,

Thai

**Comment by rakibabu** [comment]
Hi @thaiphan ,

Thanks for the feedback, I'll update this pull request this week.

Regards,

Rakhal Imming

**Comment by migarol** [comment]
@rakibabu Let me know if you need some help, i love the idea of using this for DigitalOcean, amazing :grinning:

**Comment by thaiphan** [comment]
Hey @rakibabu,

Thanks for your contribution!

I'm merging this into the develop branch and will be making some changes to it before I merge into master.

Regards,

Thai

**Pull request merged**
